version: '3'
services:
  mongo:
    image: mongo:latest
    # container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

  backend:
    build: ./backend
    container_name: DocumentScanner
    env_file:
      - ./.env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - ${DEV_PORT}:${DEV_PORT}
    volumes:
      - ./backend:/app/
    depends_on:
      - mongo

volumes:
  mongo:
